//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProProkat
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public string fullname { get; set; }
        public string address { get; set; }
        public string contact { get; set; }
        public sbyte blackliststatus { get; set; }
    }
}
