//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProProkat
{
    using System;
    using System.Collections.Generic;
    
    public partial class movies
    {
        public string name { get; set; }
        public int count { get; set; }
        public int price { get; set; }
        public string synopsis { get; set; }
        public string agerating { get; set; }
        public string genres { get; set; }
        public Nullable<System.DateTime> year { get; set; }
        public string director { get; set; }
        public string scenarist { get; set; }
        public string country { get; set; }
        public string actors { get; set; }
    }
}
