//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProProkat
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public string client { get; set; }
        public string status { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime rent { get; set; }
        public string disklist { get; set; }
        public string deposit { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> closed_date { get; set; }
    }
}
